added Contributor and implemented Ord, Eq for Pt and Mm and fixed a bug
fschutt/printpdf pull request #142
Opened 2023-06-13 08:19 UTC by JulienSchminke

Hello,

To Introduce, I am Julien and this is my first contribution on an open source project.

Firstly, I fixed this Issue https://github.com/fschutt/printpdf/issues/137. I changed the if statement so that it doesn't use the is_normal() function. Instead I check the output of the classify() function so that also zero numbers will accepted.

Secondly, I created a macro "impl_ord!" that offers the functionalities of the ord trait. I would like to add that because I am trying to implement a table method for this library and I need for that a max and a min function for the Mm type. 

Thirdly. I implemented Eq for Mm and Pt. This was required for the impl_ord Macro

I already tested it with unit tests and it works.

I would  really appreciate if you would merge it to the master branch so that everyone could benefit from the changes.

If you have any tips or ideas for me how I can contribute and help, please let me know.

Julien

2023-06-13 12:34 UTC, fschutt requested changes
Thank you, Julien (you don't have to be so formal online).

If you want to be added as a contributor, a better option is to either put it into the Cargo.toml file or in the LICENSE.txt.

2023-06-13 12:34 UTC, fschutt commented on Contributors.md
> +Julien Schminke
Add this to the Cargo.toml instead or the LICENSE.txt

2023-06-14 15:00 UTC, JulienSchminke commented
Hey, thanks for your quick response. Where shall I put my name (and maybe email) in the Cargo.toml?

Maybe at authors?

2023-06-15 05:32 UTC, fschutt commented
I would not like to have unnecessary dependencies here, also, please no tables in this crate, this stuff should go into [genpdf](https://docs.rs/genpdf/latest/genpdf/).

Please only one PR per problem, not multiple things into one PR.

2023-06-15 08:38 UTC, JulienSchminke commented
What do you mean with PR?

Oh good to know. The table stuff should't  go to your branch (also if you would accept it). I wanted to push it only on my branch.

2023-06-15 08:41 UTC, JulienSchminke commented
Do you maybe mean "push request" (PR). I only want to push the Fixed Bug commit. The rest shouldn't be pushed.
I need to know where or how to put me as a author of this crate in the Cargo.toml file and maybe how to hide the other commits with the table from this push request.

2023-06-16 09:48 UTC, fschutt commented
> I need to know where or how to put me as a author of this crate in the Cargo.toml file and maybe how to hide the other commits with the table from this push request.

Just delete the lines of code and then git commit your changes. Put yourself in the `authors = [...]` array.

2023-06-16 15:12 UTC, JulienSchminke commented
Thanks for your quick response. I've reverted the table changes and added me as an author.

2023-06-17 12:26 UTC, fschutt requested changes

2023-06-17 12:26 UTC, fschutt commented on src/table.rs
> +/*extern crate grid;
Please remove this file.

2023-06-17 12:26 UTC, fschutt commented on CONTRIBUTING.md
> -# Contribution and License
Please keep this file.

2023-06-21 15:37 UTC, merged